import os
import sys
import string

OUT_FILE_NAME = 'Android.mk'
KEEP_LIST_FILE_NAME = '.keep_list'
RESTORE_LIST_FILE_NAME = '.restore_list'
this_file_name = sys.argv[0]

cp_files_list = []

def walk_cb(arg, directory, files):
    for file_ in files:
        file_bak = file_
        if cmp(OUT_FILE_NAME,file_) == 0:
            continue
        if cmp(KEEP_LIST_FILE_NAME,file_) == 0:
            continue
        if cmp(RESTORE_LIST_FILE_NAME,file_) == 0:
            continue
        if cmp(this_file_name,file_) == 0:
            continue
        if file_.find(' ') >= 0:
            #src file name should contains no space char
            file_ = string.replace(file_,' ','_')
            os.system('mv "'+file_bak+'" '+file_)
        cp_files_list.append(file_)
        
os.path.walk('.',walk_cb,'')

if len(cp_files_list) < 1:
    sys.exit()

def write_keep_restore_line(out_file,file_extention,out_path):
    for file_ in cp_files_list:
        if file_.endswith(file_extention):
            tmp_str = out_path+'/'+file_+'\n'
            out_file.writelines(tmp_str)
            
keep_list_file = open(KEEP_LIST_FILE_NAME,'w')
restore_list_file = open(RESTORE_LIST_FILE_NAME,'w')
write_keep_restore_line(keep_list_file,'.apk','/data/app')
write_keep_restore_line(restore_list_file,'.apk','/system/appbackup')
keep_list_file.close()
restore_list_file.close()

cp_files_list.append(KEEP_LIST_FILE_NAME)
cp_files_list.append(RESTORE_LIST_FILE_NAME)

out_file = open(OUT_FILE_NAME,'w')

out_file.writelines('#generated by '+os.path.basename(this_file_name)+' for customize\n\n')
out_file.writelines('LOCAL_PATH:= $(call my-dir)\n\n')
out_file.writelines('PRODUCT_COPY_FILES += ')

def write_line(out_file,file_extention,out_path):
    for file_ in cp_files_list:
        if file_.endswith(file_extention):
            tmp_str = ' \\\n'
            tmp_str += ' $(LOCAL_PATH)/'+file_+':'+out_path+'/'+file_            
            out_file.writelines(tmp_str)

write_line(out_file,'.apk','data/app')
write_line(out_file,KEEP_LIST_FILE_NAME,'data/app')
write_line(out_file,RESTORE_LIST_FILE_NAME,'data/app')
write_line(out_file,'.apk','system/appbackup')


out_file.close()

